services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1123
      MYSQL_DATABASE: nextchat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - mongodb
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - "5001:5001"

  # client:
  #   build:
  #     context: ./client
  #   depends_on:
  #     - server
  #   environment:
  #     SERVER_HOST: server
  #     SERVER_PORT: 8080

volumes:
  mysql_data:
  mongo_data:
