/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.nextchat.server;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;


@SpringBootApplication
// @ComponentScan(basePackages = {"dev.netchat.server.utils"})
// @EnableMongoRepositories(basePackages = "com.chatapp.repository")
public class App{

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
