/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.nextchat.server;

import java.sql.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;

public class AuthenticationService{
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, NoSuchAlgorithmException {
        
        ServerSocket ss = new ServerSocket(1234);
        Socket con = ss.accept();

        BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream())); 
        PrintWriter out = new PrintWriter(con.getOutputStream(), true);

        String choice = in.readLine().trim(); 
        String username = in.readLine().trim();
        String password = in.readLine().trim();

        Authenticator auth = Authenticator.getInstance(); 
        Credential cred = new Credential(username, password);
             
        if (choice.equals("2")) {
            try {
                auth.signUp(cred);
                out.println("Account created successfully");
            } 
            catch (Exception e) { // Catching a generic exception if signUp throws any runtime exceptions
                out.println("An error occurred: " + e.getMessage());
                e.printStackTrace();
            }
        }
        else if (choice.equals("1")) {
            if (auth.signIn(cred)) {
                out.println("Login successful");
            } 
            else {
                out.println("Invalid username or password");
            }
        }
    
    }
}
