/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.nextchat.client;

import dev.nextchat.client.models.Model;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        Model.getInstance().getViewFactory().showLoginWindow();
    }
}
