/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.nextchat.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        try {
            Socket s = new Socket("localhost", 1234);
            System.out.println("Connected to server.");

            BufferedReader in = new BufferedReader(new InputStreamReader(s.getInputStream())); 
            PrintWriter out = new PrintWriter(s.getOutputStream(), true); 
            BufferedReader input = new BufferedReader(new InputStreamReader(System.in)); 

            System.out.println("Please type in your username: ");
            out.println(input.readLine()); 

            System.out.println("Please type in your password: ");
            out.println(input.readLine());

            s.close();
        } 
        
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
}
