/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.nextchat.client;

import dev.nextchat.client.backend.ServerResponseListener;
import dev.nextchat.client.models.Model;
import javafx.application.Application;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import java.net.ConnectException;

import dev.nextchat.client.backend.ConnectionManager;
import dev.nextchat.client.backend.MessageController;

@SpringBootApplication(proxyBeanMethods = false)

public class Client {
    public static void main(String[] args) {
        ConnectionManager connectionManager = new ConnectionManager();
        //Model.getInstance().preloadUserIdMapFromJson();
        try {
            String status = connectionManager.init();

            if (status.equals("FAIL")) {
                throw new ConnectException("Failed connecting to server.");
            }
        } catch (ConnectException e) {
            e.printStackTrace();
        }

        MessageController messageController = new MessageController(connectionManager);
        messageController.start();
        Model.getInstance().setMessageController(messageController);


        Application.launch(App.class, args);
    }
}
